# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf_schemas/comment_created.proto

require 'google/protobuf'

require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "protobuf_schemas.CommentCreated" do
    optional :post_id, :message, 1, "google.protobuf.Int64Value"
    optional :user_id, :message, 2, "google.protobuf.Int64Value"
    optional :body, :message, 3, "google.protobuf.StringValue"
    optional :post_comment_count, :message, 4, "google.protobuf.Int64Value"
  end
end

module ProtobufSchemas
  CommentCreated = Google::Protobuf::DescriptorPool.generated_pool.lookup("protobuf_schemas.CommentCreated").msgclass
end
